### ISSUE TITLE
Custom URL-parser matching rules

### ISSUE THREAD

**Issue by ouuan** [jmerle/competitive-companion#100]
Some online judges, including Universal Online Judge, are open-source, so many other websites besides the main website are using the same frontend.

It's nearly impossible to add all these websites in the parser choser, so it will be good if the user can add custom URL-parser matching rules.

**Comment by jmerle** [comment]
This context menu already exists specifically for that reason:

![](https://i.imgur.com/4ONkEj3.png)

**Comment by ouuan** [comment]
I only found that I could choose the parser each time, is there a way to add a rule so that I don't need to choose the parser manually each time?

**Comment by ouuan** [comment]
The rule is like a regular expression and a parser.

**Comment by jmerle** [comment]
I don't know whether I'd want to see such a rule-based system in the extension, because it adds complexity and would require a front-end.

Especially the front-end would be annoying, because due to how the green plus button is used, I cannot use the browser action popup used by extensions like uBlock Origin, but instead have to draw the front-end on the website itself. This creates tons of potential problems, simply because different websites load their content in different ways and apply their styles in different ways, which would all have to be overridden.

I do see how the current implementation is lacking though, so what would you think about a "Do you want to set GoogleParser as default parser for this hostname (www.google.com)?" dialog after using a parser from the context menu? That would solve the issue, and can be done using the native browser alert dialogs and an additional context menu entry to clear the chosen defaults. I could add that later today.

**Comment by ouuan** [comment]
> Especially the front-end would be annoying, because due to how the green plus button is used, I cannot use the browser action popup used by extensions like uBlock Origin, but instead have to draw the front-end on the website itself.

I didn't understand this :thinking:

What is "draw the front-end on the website itself"? I think it should be configured in the extension configs.

**Comment by jmerle** [comment]
I was talking about how I can't add this popup:
![image](https://user-images.githubusercontent.com/14951909/83372958-2ef74d80-a3c7-11ea-93e4-c6544a0cd26b.png)

By "drawing the front-end on the website itself" I mean adding new HTML elements to the page you're viewing and somehow forcing them to be on top of everything else you're looking at.

Adding it to the existing settings page is an interesting idea though. I'll implement that somewhere this week (I'm not sure anymore whether I have enough time today).

**Comment by jmerle** [comment]
Implemented in https://github.com/jmerle/competitive-companion/compare/f063806d75e7f6035a4e5313e126567167231218...dffd9f174e15630af4d98f0f35298a1342cba5e0:
![image](https://user-images.githubusercontent.com/14951909/83677464-802c5a80-a5dc-11ea-9102-b801c181359d.png)

Will go live later this week.

**Comment by jmerle** [comment]
I've just published 2.17.0 which contains these changes.
