### ISSUE TITLE
Problem parsing SPOJ I/O, test cases missing

### ISSUE THREAD

**Issue by DT3264** [jmerle/competitive-companion#134]
As example, with [https://www.spoj.com/problems/RPLA/](this problem), when parsing the task, the exmaple text case is missing

**Comment by jmerle** [comment]
Thanks for reporting the issue, but I won't be fixing it. The reason for that is that most problems on SPOJ display the sample cases in one or two codeblocks (like in [TEST](https://www.spoj.com/problems/TEST/)), while a small minority of problems uses a more free-form way of displaying the sample cases. The problem you linked is one of those. The issue with that is that it's pretty much impossible to write a generic parser for all those formats (since problem creators are free to display the sample cases in whichever way they like), so if the problem doesn't use the conventional format the extension won't be able to read it.
