### ISSUE TITLE
Not Parsing Problems Properly

### ISSUE THREAD

**Issue by DhruvGheewala** [jmerle/competitive-companion#143]
Parser is failing to parse problem mentioned below:

 - [MELE3](https://www.spoj.com/problems/MELE3/)

Suggestion: Keep this issue open, For a similar type of error. Because I found many problems where the parser is failing. So, each time I have to create a new issue and do the same thing. Rather you can keep this issue open. Others can also share the problem below in this thread.

I forgot other problems, which I mentioned above. I will update this thread as soon as I find those problems and I will also update this thread as soon as I find new problems.

**Comment by cryptus-neoxys** [comment]
Faced issue across CodeChef and HackerEarth where it fails to parse the problem.
Bug:
![image](https://user-images.githubusercontent.com/50591491/109890819-f6fe9d00-7cad-11eb-918b-454af68e2a34.png)

**Comment by cryptus-neoxys** [comment]
> Faced issue across CodeChef and HackerEarth where it fails to parse the problem.
> Bug:
> ![image](https://user-images.githubusercontent.com/50591491/109890819-f6fe9d00-7cad-11eb-918b-454af68e2a34.png)

Seems fixed in my Ubuntu setup.

**Comment by jmerle** [comment]
@DhruvGheewala: see https://github.com/jmerle/competitive-companion/issues/134#issuecomment-768542867. If you find problems on SPOJ for which no sample cases are parsed it is probably due to the sample cases being in free-form format, instead of the "standard" format seen in problems like [TEST](https://www.spoj.com/problems/TEST/). [MELE3](https://www.spoj.com/problems/MELE3/) is one of the problems using a free-form sample cases format. Competitive Companion only supports the "standard" format, because it's next to impossible to write a generic parser for all the different free-form formats.

As for the suggestion: I prefer to keep issues separated to make tracking them easier, and I don't believe there is a huge time difference between opening a new issue and commenting on an existing one.

@cryptus-neoxys: great to hear that you managed to fixed it, but Competitive Companion doesn't have a `contest-problem.js` file so I doubt its an error in the extension.
