### ISSUE TITLE
Properly download truncated samples

### ISSUE THREAD

**Issue by ecnerwala** [jmerle/competitive-companion#152]
Sometimes, sample inputs are truncated, for instance in Cheating Detection from CodeJam 2021 Qualification Round (https://codingcompetitions.withgoogle.com/codejam/round/000000000043580a/00000000006d1155). Maybe it would be better to always use the download link when available instead of the plaintext on the page?

**Comment by jmerle** [comment]
Thanks for reporting the issue, fixed in 2.19.2. I changed the parser so that it downloads the full text only if part of it is omitted in the code block on the problem page.

Because the full text is hosted on codejam.googleapis.com (and not codingcompetitions.withgoogle.com), the next time you try to parse a problem on Google Coding Competitions you'll need to approve the extension's access to codejam.googleapis.com so that it can make cross-origin requests. If you deny, the extension will fall back to what's visible in the code block (the partial text).

The dialog will look like this:
![](https://user-images.githubusercontent.com/14951909/112740878-b6c6cd80-8f80-11eb-923c-f5cd33a690ff.png)
