### ISSUE TITLE
testType not mapped explicitly for Codeforces

### ISSUE THREAD

**Issue by valeesi** [jmerle/competitive-companion#166]
The majority of the latest Codeforces problems are of the testType ''multiNumber" but the plugin always defaults to "single". Is this expected? I have looked through the code but couldn't find a testType mapper anywhere except for Google and Facebook rounds. 

I think the wording and DOM structure for test on Codeforces is consistent enough to make an educated guess of the testType. Perhaps this is an idea for contribution unless you are already working on this?

**Comment by jmerle** [comment]
Interesting. You're right in that multi-number is currently only used in the GCJ parser, because all GCJ problems are multi-number and I never thought about making an educated guess for it in the other parsers. Looking at the multi-number Codeforces problems this seems like a reasonable thing to do though, so I'd definitely welcome a PR for it.

**Comment by jmerle** [comment]
See https://github.com/jmerle/competitive-companion/pull/167#issuecomment-868998031.
