### ISSUE TITLE
Please support hustoj

### ISSUE THREAD

**Issue by Empathy117** [jmerle/competitive-companion#174]
It's a big open source oj [zhblue/hustoj](https://github.com/zhblue/hustoj).
there is a demo http://syzoj.hustoj.com/problemset.php

**Comment by jmerle** [comment]
The details given by @undefined-moe is why I'm closing this issue. I have no problems with adding a parser for an online judge that uses HustOJ (as long as it's an actual online judge and not just a demo website), but adding a generic parser for all online judges running HustOJ is next to impossible because of HustOJ's customizability.

**Comment by Empathy117** [comment]
Oh Thank you I didn't know that before, therefore can I ask you to add support for my school's oj?

**Comment by jmerle** [comment]
Support for BUCTOJ has been added in https://github.com/jmerle/competitive-companion/commit/2d4a2c4bea2529878f8911d6a8896daa0cae846c, released in 2.30.0.
