### ISSUE TITLE
Support short names for AtCoder (like it works for CodeForces)

### ISSUE THREAD

**Issue by orendon** [jmerle/competitive-companion#181]
A task like https://atcoder.jp/contests/abc164/tasks/abc164_d could be translated to `abc164_d`

This is similar to how it currently works with CodeForces, what do you think?

**Comment by jmerle** [comment]
That's definitely not how the Codeforces parser works at the moment, when parsing [1559E](https://codeforces.com/problemset/problem/1559/E) the name is parsed as "E. Mocha and Stars" instead of "1559E".

I'm not planning on changing this. I think "EMochaAndStars" is better than "1559E" when you're participating in a contest with multiple problems. Especially when having to differentiate between different problems having the full name instead of just the letter can be very helpful.

Additionally, even though the extension parses it as long names, there is enough information in the extracted data to convert the names to short variants like "1559E" or "abc164_d" in third-party tools.

**Comment by orendon** [comment]
Thanks for pointing that out, I investigated further and the short name is being done by a third-party tool that uses   `compeitive-companion` as a dependency 👍🏿
