### ISSUE TITLE
Still tests are parsing incorrecly

### ISSUE THREAD

**Issue by emli** [jmerle/competitive-companion#19]
https://acmp.ru/index.asp?main=task&id_task=787

![image](https://user-images.githubusercontent.com/5517490/50143148-07491e00-02d6-11e9-93ba-4239b45116d1.png)

**Comment by jmerle** [comment]
As I said in https://github.com/jmerle/competitive-companion/issues/18#issuecomment-447517014, it is fixed in the develop branch but has yet to be published on the Chrome Web Store and Mozilla's AMO because I'm working on some other features too that I want to go into that same release. I'm planning to finish those features this weekend.
