### ISSUE TITLE
Contest parser fallback when problem parser fail

### ISSUE THREAD

**Issue by user202729** [jmerle/competitive-companion#196]
Sometimes, because of some unimplemented cases the problem parser may fail on some problems in the contest, and success in others.

In such cases, it would be better to send (only) the successfully parsed problems and let the user manually type in the rest.

----------

Actually I came across this issue when parsing a Yandex contest that does not have a time limit, but because it has recently been fixed, it's no longer reproducible now.

**Comment by jmerle** [comment]
I disagree. If some of the problems cannot be parsed I rather have it throw an error than have it send some of the problems to the user's tool, because if part of a contest cannot be parsed that's a bug in the contest parser and I rather have it explicitly fail in that case (so that users report it and so that you don't need to check every time whether there were unparsed problems).

**Comment by user202729** [comment]
But still, assume that you're really in some contest, you would not be able to make a bug report then wait for developer's reply within that 5 hours.

Perhaps make a warning for the user with "please make a bug report" or something.

**Comment by jmerle** [comment]
When a contest parser breaks during the contest you're right that it probably won't be fixed before the end of it, but keep in mind that you can always use the problem parser on each task separately.

I've been thinking about this suggestion a bit more. Although it sounds like a useful feature and I don't have strong arguments against it, it doesn't feel right to me to change how error handling in contest parsers works because there _may_ be bugs in the underlying problem parsers. That's basically the exact opposite of "tackling a problem by its roots", which makes it close to an anti-pattern in my book.

Nonetheless, I can see how having to try to parse each problem separately when a contest parser fails on a subset of the problems is not exactly a good user experience. As such, I will implement your last suggestion in which the contest parser shows an alert in case of partial parsing failure, but does send the successfully parsed problems to the user's tool after the user acknowledges the alert.

I've got a partial implementation of this change in a local development version of the extension which I'll finish within a day or two. I'll re-open this issue and let you know when it's finished.

**Comment by jmerle** [comment]
Implemented in https://github.com/jmerle/competitive-companion/commit/41dc9e428a347f26d9c4c692f20bdb0c01080f2b, released in 2.29.0. The alert looks like this:
![](https://user-images.githubusercontent.com/14951909/140776665-187f75c9-3e36-4877-81e8-754f167fa941.png)
