### ISSUE TITLE
New OJ

### ISSUE THREAD

**Issue by fcfcfcfcfcfcfc** [jmerle/competitive-companion#207]
Could you support the submission of www.hydro.ac

**Comment by jmerle** [comment]
No, this extension does not support submission to any online judge, because I consider that to be outside the scope of this extension.

However, I did just notice that the parsing of problems and contests on Hydro is broken, so that's fixed in https://github.com/jmerle/competitive-companion/commit/d421882b682163a5b6256d7a3d458ac677f0ff16 which will be released soon.
