### ISSUE TITLE
Is it broken for AtCoder ?

### ISSUE THREAD

**Issue by anshumishra** [jmerle/competitive-companion#21]
Looks like it is not working for AtCoder. It used to work couple of days back. I have tried using it on Mac/Chrome as well as on Windows/Chrome. It does work for other sites though such as CodeForeces, CSAcademy, etc.

**Comment by anshumishra** [comment]
I am using "CHelper" by the way.

**Comment by jmerle** [comment]
Yep, the latest version does not support AtCoder at the moment because they recently made the beta version the default. This change caused Competitive Companion's match pattern for AtCoder to fail, which was fixed in #20. This change will go live somewhere in the next 2 days, so until then it won't work.

I will close this issue when the update is released.

**Comment by anshumishra** [comment]
Thanks for such a fast response ! Appreciate it and really love this plugin !!!

**Comment by jmerle** [comment]
I released version 2.5.0 with the AtCoder fix in it. It can take up to 24 hours for the browser to automatically update the extension.
