### ISSUE TITLE
Trailing spaces on each line are removed in test cases

### ISSUE THREAD

**Issue by user202729** [jmerle/competitive-companion#210]
Which will affect problems such as https://open.kattis.com/problems/ads .

Looks like it's explicitly written at https://github.com/jmerle/competitive-companion/blob/ece807875ddc91e0b07958769438937ee8919df0/src/models/Test.ts#L16.

Commit: https://github.com/jmerle/competitive-companion/commit/5dbcf3b63d9ab821175b795ad55a1e6e549a9a87

I think in these cases it's better to modify the individual problem parser instead of globally modify in Test constructor. (... with almost 100 supported sites it would be hard.)

**Comment by jmerle** [comment]
Fixed in https://github.com/jmerle/competitive-companion/commit/cea5457f7e8269e0df76688d54e591a98702fa3d. I added a `normalizeWhitespace` parameter to `TaskBuilder.addTest` that defaults to `true`, because this is the first bug report about it in ~9 months so for most judges it seems perfectly fine to do this. It also makes adding support for new judges a little easier, so unless more problems with the normalization are found I'm planning to keep it the way it is. Will be released later today.
