### ISSUE TITLE
Should support for Codeforces problems with only PDF statements be added?

### ISSUE THREAD

**Issue by user202729** [jmerle/competitive-companion#215]
Some problems e.g. https://codeforces.com/gym/103492/problem/H have the statement directly link to a PDF, which breaks the Codeforces contest parser.

Of course in this case it's not possible to parse sample test cases, but for parsing the problem do you think it would be a good idea to

* Parse the time/memory limit from contest problems page/submit page?
* Report the URL as the /problem URL or https://codeforces.com/gym/103492/submit/H ? The former is not a valid website for tools such as cpbooster to submit to.

**Comment by jmerle** [comment]
We do have a way to read PDFs in the extension ([`readPdf`](https://github.com/jmerle/competitive-companion/blob/2d932d1c4a0cf7d118ee7def85c1170b1ca805ed/src/utils/pdf.ts)) which is used for UVa Online Judge and ICPC Live Archive problems, but it seems like the structure of the Codeforces PDFs cannot be parsed well enough for this function to be useful.

Taking the available information from the contest page as you suggest sounds like a good idea, I've implemented that in https://github.com/jmerle/competitive-companion/commit/2d932d1c4a0cf7d118ee7def85c1170b1ca805ed.

For consistency I won't be changing the URL though, as the URL of all parsed problems is the link to the problem itself, not to its submission page. If tools like cpbooster cannot handle certain problem URLs, then I consider that a bug in the external tools which can easily be fixed by programmatically converting the problem URL to the submit URL (`url.replace('/problem/' , '/submit/')` seems to do the trick in the case of Codeforces).
