### ISSUE TITLE
Can this be used standalone?

### ISSUE THREAD

**Issue by shadmansaleh** [jmerle/competitive-companion#217]
Can this be ran under `node` to parse problems from url ? If not is there any plan on adding such support ?
I think it would have been quite useful if some tool could just spawn it and tell it parse certain problem .
This might be an easy or hard to add support depending on how much current implementation relays on browser.

**Comment by jmerle** [comment]
Although the parsers can be adapted to use a library like JSDOM instead of the browser's DOM APIs (which is already done for tests), the biggest hurdle is that some/many parsers are made to parse _rendered_ content. In other words, they won't work if you pass them the raw HTML retrieved via an HTTP GET call on a problem or contest url.

Finding out exactly which parsers are affected by this and refactoring them to support raw HTML is a very lengthy task, and may not even be feasible for all parsers. I don't want to release a Node.js library that may or may not work for URLs from [supported websites](https://github.com/jmerle/competitive-companion#supported-websites), so for now this won't be supported.
