### ISSUE TITLE
Extention not Working

### ISSUE THREAD

**Issue by rishabhdeepsingh** [jmerle/competitive-companion#23]
Hey, I am tried using this extension for both CHelper (IntelliJ Idea) and JHelper(Clion) But it is not parsing any Problem to the IDE.
I am using Linux and my internet is behind a proxy.

**Comment by rishabhdeepsingh** [comment]
I tried many Problems from codeforces and codechef also but its not working on any of them.

**Comment by rishabhdeepsingh** [comment]
I think the problem is with Linux as it works fine with proxy on my Windows system.

**Comment by jmerle** [comment]
Because it is a browser extension, web requests automatically inherit the proxy settings of the browser, which in most cases inherits its settings from the system. I can ensure that the extension does work on Linux when not using a proxy, since all my private machines run Linux.

Could you please turn on debug mode (right-click on the green plus -> Options) and try to parse a problem with the console open (F12 > Console tab)?

**Comment by rishabhdeepsingh** [comment]
It works on the windows but not on linux. It just shows a green line at top and then nothing happens on the IDE. I Tried the Debug mode but it is showing only a JSON.
```
{
    "name": "C. Prefixes and Suffixes",
    "group": "Codeforces Round #527 (Div. 3)",
    "url": "https://codeforces.com/contest/1092/problem/C",
    "interactive": false,
    "memoryLimit": 256,
    "timeLimit": 1000,
    "tests": [
        {
            "input": "5\nba\na\nabab\na\naba\nbaba\nab\naba\n",
            "output": "SPPSPSPS\n"
        },
        {
            "input": "3\na\naa\naa\na\n",
            "output": "PPSS\n"
        },
        {
            "input": "2\na\nc\n",
            "output": "PS\n"
        }
    ],
    "testType": "single",
    "input": {
        "type": "stdin"
    },
    "output": {
        "type": "stdout"
    },
    "languages": {
        "java": {
            "mainClass": "Main",
            "taskClass": "CPrefixesAndSuffixes"
        }
    }
}
```

**Comment by jmerle** [comment]
At least that JSON ensures that the parser is working correctly. Since this basically confirms it is a proxy issue, there's nothing I can do on the side of the extension to fix it. Proxy settings are handled by the browser, and all requests the extension makes basically inherit these settings. There's nothing I can change about that.

Could you go to `chrome://linux-proxy-config/` to see if Chrome is picking up your system's proxy configuration correctly? If it is not, that might be your problem.

**Comment by rishabhdeepsingh** [comment]
I think its a Proxy issue with Chrome as it is working on the Firefox.
Thanks for the Help :smile:
