### ISSUE TITLE
Small issue with the virtual judge parser for zoj problems

### ISSUE THREAD

**Issue by landcold7** [jmerle/competitive-companion#24]
Hi!, first of all, thanks for your efforts to build this awesome extension, really saved a lot copy-pasting time.

My issue here is that the parser for zoj problems in vritual judge platform seems not working sometime. here is a picture showing this issue. 

Add following links for you to verify, I was planning to fix by myself then to pull a request, but i didn't have any experience with node.js, so sad. :-) Have a nice day!
https://vjudge.net/problem/ZOJ-1586
https://vjudge.net/problem/ZOJ-1610
https://vjudge.net/problem/ZOJ-3209
https://vjudge.net/problem/ZOJ-3496

![image](https://user-images.githubusercontent.com/10767369/51534926-177a8d00-1e82-11e9-84b6-b13d29046274.png)

**Comment by jmerle** [comment]
Good catch. Since vjudge does not have a standarized format for problems, it's not possible to have a 100% bulletproof solution. Instead, the extension tries to do it's best at detecting what text is a testcase and what is not.

I'll improve the "detection algorithm" to fix the issue with the problems you linked tomorrow.

**Comment by jmerle** [comment]
I improved the Virtual Judge parser in 973be54d90c4d19c7119f96b28a43bbeee06343f, which fixes the issue for problem 1586. For problem 1610, it detects the testcase but isn't able to see that the "1 1" in the output is surrounded by newlines. This is because there are no actual newlines, it's only made to look like that by giving the paragraph some extra padding:

![](https://i.imgur.com/KkXYTRA.png)

Unfortunately, I won't be able to fix that issue, so you'll have to manually edit the testcase there.

I have released the commit linked above in version 2.5.2. Your browser should auto-update the extension within 24 hours.
