### ISSUE TITLE
CPH doesn't work with the new CodeChef UI

### ISSUE THREAD

**Issue by RoyCoding8** [jmerle/competitive-companion#267]
After codechef changed it's new UI slightly (by adding some features for Pro users), CPH has stopped working with it.

![image](https://user-images.githubusercontent.com/92641125/179794293-5e8233d8-73a6-4a00-b74e-21371b2998da.png)

Although there is a workaround (Switch to Old Problems Page  --> Then use 'cph'), it would be nice to have a fix for this...

**Comment by jmerle** [comment]
This is most likely a duplicate of https://github.com/jmerle/competitive-companion/issues/250#issuecomment-1186421216, which was fixed in 2.35.0 about 4 hours ago. Going by that error message you're still running an old version (not your fault, browsers don't auto-update installed extensions instantly), please re-install the extension so you have the latest version and try again.

**Comment by RoyCoding8** [comment]
Okay, thanks a lot!
