### ISSUE TITLE
Luogu Parser Error

### ISSUE THREAD

**Issue by rogeryoungh** [jmerle/competitive-companion#296]
When I open the problem solution page first(like [link](https://www.luogu.com.cn/problem/solution/P1001), need login), and then return to the problem page(click "返回题目"), the parser will report an error.

Refresh the title page could solve it. 

https://github.com/jmerle/competitive-companion/blob/bd3a8b0426bef378c7a9b11d3eb123cdb5289727/src/parsers/problem/LuoguProblemParser.ts#L28-L43

The parser seems to parse the json in the  `<script>` directly, not through the current page element.

**Comment by jmerle** [comment]
Fixed in 791954e41ca74e6ef74ec34c3fe61f35041dd6ca, will be released within a few hours.

The reason why the parser parses the data in the `<script>` tag directly is to make the contest parser work. When the contest parser requests a problem page, some problem details are not provided in HTML elements but are instead encoded in the data in the `<script>` tag. I've changed it so that the parser detects whether the page has rendered or not, and based on that either parses the data from the page or from the data in the `<script>` tag.
