### ISSUE TITLE
Don't work on Eolymp anymore.

### ISSUE THREAD

**Issue by mammadow** [jmerle/competitive-companion#343]
After some UI changes update on Eolymp this extension don't show testcases and when parsing contest don't parse every problem. When I parse a problem it makes name of file like "My Solution". Here is screenshot:
![image](https://user-images.githubusercontent.com/88704613/230738434-8d3d4311-8122-4259-81bf-95d7b4d454a8.png)

**Comment by jmerle** [comment]
The parsing issue is fixed in 4eba3fff3823e9f81f0a36de31fa20957fe68274 and will be released in a few hours. Thanks for reporting the issue!

As for the file naming, Competitive Companion is only in control of extracting the problem data. Any files created on your local disk is done by the tool Competitive Companion is sending the extracted data to (CPH in this case it seems), meaning this is not something that can be fixed in this project. It could, however, be possible that the broken Eolymp parser gave CPH incorrect/partial information leading to a file named "My_Solutions.cpp" (which sounds like a fallback name).
