### ISSUE TITLE
It displays abnormally when any line of expected output have space

### ISSUE THREAD

**Issue by clark-forever** [jmerle/competitive-companion#345]
It displays abnormally when any line of expected output have space, please fix it. For example, https://onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=4&page=show_problem&problem=163

**Comment by jmerle** [comment]
Thanks for reporting the issue! Fixed in 02579be3af6a6766a69b814927a23fad3f947b71, will be released within a few hours.

Please note that it may still be imperfect. Parsing sample cases from PDF files is tricky because the PDF parser used by Competitive Companion ([PDF.js](https://mozilla.github.io/pdf.js/)) only exposes where chunks of text are located on the page in terms of (x, y) coordinates. The spaces you're mentioning are not part of these text chunks, but are rather empty whitespace that text is located around, so I updated Competitive Companion to estimate how many spaces the empty whitespace represent.

This is approach only solves the issue for leading spaces between the left margin and the start of the line and for spaces in between chunks of text on the same line, if there are problems with sample cases containing trailing spaces at the end of a line then Competitive Companion will still leave those out of the test case. I don't know what a fix for that issue would look like yet (or whether it's possible to fix with PDF.js in the first place), please let me know if you happen to come across a problem with such a sample case.
