### ISSUE TITLE
Extension is not working on firefox

### ISSUE THREAD

**Issue by Yaksham** [jmerle/competitive-companion#349]
Tried with multiple sites like CF, Codechef, CSES.

**Comment by jmerle** [comment]
I just tried parsing a Codeforces problem on Firefox and it seems to be fine on my end:
![](https://github.com/jmerle/competitive-companion/assets/14951909/74588983-abb7-42cd-849b-42fbbe29108e)

Can you please turn on Competitive Companion's debug mode by right-clicking on the green plus icon > Manage Extension > Preferences > Debug mode? After doing so, go to a problem page (like [https://codeforces.com/problemset/problem/1829/H](https://codeforces.com/problemset/problem/1829/H)), open the browser console (F12 > Console), and click on the green plus icon. Do you see a JSON object pop up like in the screenshot above?

**Comment by Yaksham** [comment]
I do see the JSON object but the problem does not appear in VSCode.
I tried with chromium (edge) and it seems to be working fine on that.

I tried reinstalling both the firefox and vscode extension but that didnt help.

**Comment by jmerle** [comment]
If you see the JSON object the problem is most likely in the VS Code extension, not in Competitive Companion. Competitive Companion only parses problems and sends the extracted data to external tools (such as the VS Code extension you're using), and if you see the JSON object in the browser console that means the problem was successfully parsed and broadcasted to external tools that are listening. These external tools are not made or maintained by me, you should report this issue to the developer(s) of the VS Code extension you're trying to use.

**Comment by Yaksham** [comment]
Ah I see, I'm using [Competitive Programming Helper (cph)](https://marketplace.visualstudio.com/items?itemName=DivyanshuAgrawal.competitive-programming-helper).

Since it works fine with edge, I thought the issue might have been in the firefox extension.
I do see a similar issue open in cph's repo, but its been almost a year with 0 response.

Feel free to close this, but can you suggest any potential steps I could take to debug this a bit myself?

**Comment by jmerle** [comment]
My advice is probably not worth anything anymore because of the delay, but that error means there's already some program listening on the port (perhaps another VS Code window running CPH, perhaps something else).
