### ISSUE TITLE
not opening the problem

### ISSUE THREAD

**Issue by Devansh0301** [jmerle/competitive-companion#352]
![image](https://github.com/jmerle/competitive-companion/assets/130764624/6364f606-e303-42ae-8c78-f24228e8fffb)
![image](https://github.com/jmerle/competitive-companion/assets/130764624/72af2786-c2a9-4f1a-8a62-322180e61b02)

**Comment by jmerle** [comment]
You seem to be running a third-party distribution of Competitive Companion, because the official version doesn't have a "AlgoZenithLearningProblemParser". I added support for AlgoZenith to the official version of the extension in 5e47857d689f456caccbc45ec5ea72a77ffca308, which will be released within an hour. I recommend reinstalling the extension through one of the official channels [listed in the readme](https://github.com/jmerle/competitive-companion#install) once 2.43.0 is live.
