### ISSUE TITLE
Can add competitive programming parser for geeksforgeeks practice website

### ISSUE THREAD

**Issue by Rishabhsahu325** [jmerle/competitive-companion#376]
I think that it will be very beneficial if this problem parser works with Geeksfor geeks (https://practice.geeksforgeeks.org/problems/) practice website as well which is used by many people preparing for interview preparation and this site also has driver code filled up so it should be compatible to run and check the test cases. Currently there is no parser for geeks for geeks.
2)With this I also thought of another feature idea of some advanced feature wherein users can click on particular regions of any new encountered  problem submission website and save it as configuration for all problems of that website. Since I don't know if this second suggestion is acutally possible and feasible or not I did not add it as a separate issue .

**Comment by touhidurrr** [comment]
@Rishabhsahu325 https://github.com/jmerle/competitive-companion/issues/245

**Comment by jmerle** [comment]
@touhidurrr is right about the first half of your question, despite GeeksforGeeks providing the driver code its problems still don't fit the type of problems that Competitive Companion is built for.

I'm also not going to implement your second suggestion, because I much prefer users create a new issue here so a full parser can be added for the online judge that all users can then use, rather than just the person that hand-built a custom parser for it. It would also be a harder feature to build and use than just prompts like "select element containing time limit", because often there is post-processing needed on the content of selected elements (e.g. extract part of the content of an element, multiplying/dividing it, removing unnecessary whitespace, etc.).
