### ISSUE TITLE
extension not working on edge

### ISSUE THREAD

**Issue by Aneket-Burman** [jmerle/competitive-companion#378]
https://codeforces.com/contest/1878/problem/A

**Comment by jmerle** [comment]
I just tried parsing that problem on Edge and it seems to work fine on my end:
![](https://github.com/jmerle/competitive-companion/assets/14951909/4562059a-e230-44be-937a-89cb4945118b)

Can you please turn on Competitive Companion's debug mode by right-clicking on the green plus icon > Extension option > Debug mode? After doing so, go back to the problem, open the developer tools (F12 > Console), and click on the green plus icon. Do you see a JSON object pop up like in the screenshot above?

**Comment by touhidurrr** [comment]
@jmerle same for #373 and #375. Couldn't reproduce from my side.

**Comment by touhidurrr** [comment]
And people who opened these issues stopped responding after opening them. Maybe we should close these and see if there are new issues of similar kind.

**Comment by jmerle** [comment]
I've closed the 2 issues you've commented on, but I'm leaving this one open a bit longer. I tend to close issues after at least a month without activity, I sometimes also take a few weeks to reply so it feels unjust to expect others to reply sooner.

As for pro-actively hunting down issues in parsers: for some parsers there are tests (`pnpm test` to run them in a headless browser, `pnpm test:no-headless` to see the browser), but they are not running automatically anymore because of how flaky they are. Some tests fail when you run `pnpm test`, but succeed when you run them one-by-one. Other judges go offline temporarily at seemingly random times, or are very slow to access (mostly Chinese judges), slowing down tests a lot. At this point in time the test framework mostly serves as a TDD framework to help implementing parsers, but isn't used to pro-actively hunt down bugs.

Instead, for the past while I've resorted to just fixing parsers that are reported to be broken. The downside to this is that when a parser is broken, it may take a while for it to be fixed. On the other hand, most Competitive Companion users are developers themselves, so I expect them to know how to report issues and be more likely to do so than average browser users. This approach saves a lot of time maintaining the extension, and generally seems to work well based on how review scores and user growth haven't decreased.

**Comment by touhidurrr** [comment]
testing aside, `yarn lint`  /  `pnpm lint` or `yarn fix` / `pnpm fix` also does not work me. I have to manually type `pnpm fix:prettier` to get it working. 😆

I am not a pnpm user so maybe you can look into it. although this looks like topic of another issue.
