### ISSUE TITLE
DOMjudge testcases broken in Firefox since Manifest V3

### ISSUE THREAD

**Issue by ItsNiklas** [jmerle/competitive-companion#407]
In the release version of the extension/on master, the DOMjudge contest parser is unable to extract the testcases (from zip).

Here's what I found out.
- The error is `Error: Can't read the data of 'the loaded zip file'. Is it in a supported JavaScript type (String, Blob, ArrayBuffer, etc) ?` from JSZip trying to read the ArrayBuffer.
https://github.com/jmerle/competitive-companion/blob/68dcedf14692b8750f74ad367153549dbe3a2568/src/parsers/contest/DOMjudgeContestParser.ts#L79-L81
- The actual contents of the ArrayBuffer _seem_ to be fine, as when converted to a string, some correct strings can be identified in the compressed artefact... The length also varies from problem to problem.
- `git-bisect` revealed [`0908810`](https://github.com/jmerle/competitive-companion/commit/09088108a53f98bdb2f5b62c7b9995c8045fae37) as the first bad commit.
- The issue only occurs only in Firefox, not in `dev:chrome`.

This is quite intriguing, but I don't know enough about web extensions to solve it myself.

**Comment by jmerle** [comment]
Weird issue, but fixed in 0f96a0cb2d661d87737e5c99e2ec44888d75285a. I have no clue what's going on, but this appears to be the same issue as https://github.com/Stuk/jszip/issues/759, and the workaround for that issue posted in https://github.com/Stuk/jszip/issues/759#issuecomment-932896399 also works here.
