### ISSUE TITLE
Parse failed test cases on Codeforces

### ISSUE THREAD

**Issue by weeebdev** [jmerle/competitive-companion#408]
Parse failed test cases that open only after submission.
They can be found on `https://codeforces.com/contest/1921/submission/241817475`, for example.
Idk, probably parse it only on problem page and receive via `:Competitest receive testcases`

**Comment by jmerle** [comment]
I vaguely remember receiving this feature request a few years ago, but can't find it anymore. Anyways, I'm not planning on implementing this because Codeforces truncates the inputs and outputs of testcases on those submission pages. For example, on the page you linked you can see that the input of the second testcase is truncated, and therefore not usable in local test runners.

**Comment by weeebdev** [comment]
> I vaguely remember receiving this feature request a few years ago, but can't find it anymore. Anyways, I'm not planning on implementing this because Codeforces truncates the inputs and outputs of testcases on those submission pages. For example, on the page you linked you can see that the input of the second testcase is truncated, and therefore not usable in local test runners.

Oh, I see. I thought it could be retrieved from an API.
