### ISSUE TITLE
Parsing failed in codechef

### ISSUE THREAD

**Issue by anil1807** [jmerle/competitive-companion#410]
**VM42 common.js:1  TypeError: Cannot read properties of null (reading 'textContent')
    at CodeChefNewProblemParser.parse (VM42 common.js:1:383899)
    at p (content.js:1:580)
    at content.js:1:1510**

I got this error while trying to parse this page -link- https://www.codechef.com/START118D/problems/JOINSTATE

thank you

**Comment by PRATHAM2107** [comment]
content.js:1 TypeError: Cannot read properties of null (reading 'textContent')
    at CodeChefNewProblemParser.parse (common.js:1:383899)
    at p (content.js:1:580)
    at content.js:1:1510
    Same Issue

**Comment by jmerle** [comment]
Fixed in 58d8203d5f8da9ea5105fe3a57a0d59a32e7a114, thanks for reporting the issue! I'm not sure when it will be publicly available, I hope to have a release out within 24 hours but the last Chrome Web Store release was rejected, so it may take a while for it to be available there (the updated version will probably be available on Firefox and for manual installation on Chrome within 24 hours though).
