### ISSUE TITLE
Competitive Companion Chrome Version

### ISSUE THREAD

**Issue by lkaesberg** [jmerle/competitive-companion#413]
Hello,
I've seen that the new version of Competitive Companion implements a parser for DOMJudge, but Chrome is still a few versions behind. Do you have any idea when it will be released in the Chrome store?

**Comment by jmerle** [comment]
Soon, hopefully. The Chrome Web Store release for 2.49.0 was rejected, presumably because the extension sends parsed problem data to local applications over HTTP rather than HTTPS. I've contacted the Chrome Web Store team through their contact form to explain why the extension uses HTTP rather than HTTPS, and in a subsequent re-review they deemed it compliant with their privacy policy. Unfortunately they cannot approve a previously rejected submission, so upon their request I've re-submitted the rejected submission (2.49.0), and I expect that version to be published successfully soon. Once that happens I'll also submit the latest version (2.50.0) to the Chrome Web Store.

**Comment by jmerle** [comment]
2.50.0 is now available in the Chrome Web Store, closing this issue.
