### ISSUE TITLE
Cant parse codechef contest

### ISSUE THREAD

**Issue by Siddho** [jmerle/competitive-companion#419]
content.js:47 TypeError: Cannot read properties of null (reading 'textContent')
  this is the error i am facing regarding codechef contest.
[https://www.codechef.com/START119C/problems/ADVITIYA2](url)

**Comment by 1TusharSharma1** [comment]
Same

**Comment by Siddho** [comment]
[https://github.com/jmerle/competitive-companion/releases](url)
I have installed latest release too but the same error is persisting

**Comment by jmerle** [comment]
> [https://github.com/jmerle/competitive-companion/releases](url) I have installed latest release too but the same error is persisting

I can't reproduce this issue on 2.50.0, and given how Chrome works this may be user error (Chrome could be more clear here). If you have the Chrome Web Store version installed and then manually install an unpacked version of the same extension, you'll have 2 green plus icons in the browser actions with the exact same label:
![](https://github.com/jmerle/competitive-companion/assets/14951909/64d2b882-5c1d-4361-ae3f-f79012e7a557)

If you pinned the green plus icon button to the area to the right of the URL bar, that button was probably still triggering the Chrome Web Store version of the extension, rather than the unpacked install. 2.50.0 is now available through the Chrome Web Store as well, could you try uninstalling the unpacked version, ensure the Chrome Web Store-install is at version 2.50.0 (at `chrome://extensions/?id=cjnmckjndlpiamhfimnnjmnckgghkjbl`), and try to parse the problem again? If it still doesn't work, please post a screenshot of the full stacktrace.

**Comment by Siddho** [comment]
@jmerle it seems the parsing error was doing live  contests,now its working fine
