### ISSUE TITLE
not working in Algozenith site

### ISSUE THREAD

**Issue by ShubhamMishra2526** [jmerle/competitive-companion#435]
https://maang.in/problems/Minimise-Max-Diff-46?resourceUrl=cs85-cp500-pl3350-rs46

**Comment by jmerle** [comment]
Fixed by #433.

**Comment by ShubhamMishra2526** [comment]
Still not working

**Comment by jmerle** [comment]
That's because the changes in #433 have not been released yet, that'll happen within a few hours. After that it'll take anywhere between a few minutes and a few days for the release to be reviewed by the Chrome Web Store (and Mozilla's AMO), after which it can take another ~24 hours for browsers to auto-update the extension to the latest version.

**Comment by ShubhamMishra2526** [comment]
Ok, thanks for the clarification.
