### ISSUE TITLE
Samples couldn't be crawled when the "sample" label is non-English in Vjudge

### ISSUE THREAD

**Issue by Yerosius** [jmerle/competitive-companion#446]
In Vjudge, when the "Sample" label is non-English, it will lead to failure to crawl samples.

The  situation will be caused when the statement is non-English or using Vjudge's GPT translation into a non-English language.

**Comment by Yerosius** [comment]
By the way,when the statement is provided in document form(such as UVA OJ),the samples can't be crawled,too.

**Comment by touhidurrr** [comment]
Hi, @Yerosius. Can you provide some links so that I can test this?

**Comment by Yerosius** [comment]
such as the flowing problem: https://vjudge.net.cn/problem/Gym-104385A#author=GPT_zh



---- Replied Message ----
| From | Md. Touhidur ***@***.***> |
| Date | 05/25/2024 21:31 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [jmerle/competitive-companion] Samples couldn't be crawled when the "sample" label is non-English in Vjudge (Issue #446) |

Hi, @Yerosius. Can you provide some problem links so that I can test this?

**Comment by jmerle** [comment]
I've fixed the parsing of sample cases on Chinese problems like the one you linked in d592027aae57765ed3e2fc9ca011caa3412f91fe, and added support for parsing sample cases on UVA and UVALive problems in 3b4ed00e98a19dfe9d20f86880d051c85eb48a9a. The latter only works in Chrome for now due to a bug in Firefox (https://bugzilla.mozilla.org/show_bug.cgi?id=1757836), it's prioritized as P2 which means that it should be fixed in Firefox's next release cycle or the following. Thanks for reporting the issues!
