### ISSUE TITLE
Competitive companion extension not working for Codechef

### ISSUE THREAD

**Issue by Vedhamshbode** [jmerle/competitive-companion#460]
I am not able to use the extension for Codechef, this happened to many of frnds too, if there's a minor bugs please fix it.[
![Screenshot from 2024-05-16 10-51-21](https://github.com/jmerle/competitive-companion/assets/142669807/d97e79c1-a7cf-4772-9c10-67e7a3af1052)
](url)

**Comment by jmerle** [comment]
This issue was fixed in [2.52.1](https://github.com/jmerle/competitive-companion/releases/tag/2.52.1), which went live about a week ago. When this issue was created the Firefox release was already published to Mozilla's AMO, but the Chrome release was still pending review on the Chrome Web Store (it was approved 6 hours later). Between then and now your browser should have auto-updated the extension to the latest version, if that's not the case you should be able to force the update by re-installing.

Please let me know if the issue still persists, but for now I consider it fixed.
