### ISSUE TITLE
can't parser problem on OJ made from HUSTOJ

### ISSUE THREAD

**Issue by f2666** [jmerle/competitive-companion#488]
OJ[demo.husto.com](url)

[https://github.com/zhblue/hustoj.git](url)

**Comment by f2666** [comment]
the OJ i use that can parse:[gdgzoi.com](url)

**Comment by jmerle** [comment]
I can't reach gdgzoi.com, making it hard to add a parser for it. Can you please check whether right-clicking on the green plus icon and selecting Parse with > Problem parser > BUCTOJProblemParser on a problem page on gdgzoi.com works without errors?

**Comment by touhidurrr** [comment]
Well now this judge is online but I cannot see problems because of the tedious registration progress. Don't want to fill in wrong info to register. This judge seems to be a private judge intended for only a particular educational institute.
Thus, I would argue if we even need to support this as this is not a public judge.

**Comment by jmerle** [comment]
I'm not against adding parsers for private judges, but such parsers need to be contributed by and kept up-to-date by users of the private judge. In this case it seems you're right, registration requires administration approval which likely means you need to be enrolled at one of institutes the judge was set-up for.

In other words, if someone with access to the judge wants to contribute a parser for it, feel free to open a PR. I am closing this issue though, as there's nothing more I can do from a maintainer's point-of-view.
