### ISSUE TITLE
`TimusOnlineJudge` not used automatically

### ISSUE THREAD

**Issue by goyalyashpal** [jmerle/competitive-companion#492]
### Summary

* it is not being able to automatically detect which parser to run on the given link
* however, on manually choosing the "parse with" > "problem parser" > "TimusOnlineJudgeProblemParser"  - it works

### Proposals

I think this is an example of linkrot, where the link format stored in extension has become outdated.
so:

give some option in extension so that user can:
1. manually specify the link pattern for a particular problem parser
2. specify a default problem parser - which is chosen regardless of current sites link

### details about error

Message:

> Competitive Companion could not determine which parser to parse this page with. Please right-click on the plus icon and select the parser to use via the "Parse with" context menu. Please open an issue at https://github.com/jmerle/competitive-companion/issues if you think this is a bug (make sure to include a link to this page).

* link: https://acm-judge.urfu.ru/problem.aspx?space=1&num=1100
* browsers: 
  * librewolf: v130.0 (based on firefox)
  * brave: Version 1.69.168 Chromium: 128.0.6613.138 (Official Build)  (64-bit)
* os: nixos v24.11.20240916.99dc878 (Vicuna)
* extension: v2.54.0

**Comment by jmerle** [comment]
Fixed in e30e82cf49e53837dd39bf15330d214f19a33b71, will be released around Monday. Thanks for reporting the issue!

I don't think this classifies as linkrot as the two Timus domains that Competitive Companion's parsers support are still up-to-date as far as I'm aware (https://acm.timus.ru/ and https://timus.online/). https://acm-judge.urfu.ru/ is a Timus mirror I wasn't aware about. Either way, your first proposal is already supported in the extension's settings underneath the "Custom rules" header.

**Comment by goyalyashpal** [comment]
thanks a lot :)

* just noting a similar issue for this mirror in a different extension :laughing: 
* https://github.com/borzunov/timus-charts/issues/3
