### ISSUE TITLE
Algozenith Old and new Problem Parsers are not working

### ISSUE THREAD

**Issue by Acadaniket-2001** [jmerle/competitive-companion#496]
plz look into the issue, parser are still not working

**Comment by jmerle** [comment]
Version 2.55.0 contains the fix for this issue. It has already been approved for publication on Mozilla's AMO, but is still pending review in the Chrome Web Store. In other words, please be patient for the Chrome Web Store release to go live, switch to Firefox, or manually install the latest release as described in https://github.com/jmerle/competitive-companion/issues/26 (don't forget to switch back to the Chrome Web Store version later to get automatic updates to future versions).

**Comment by Acadaniket-2001** [comment]
thanks @jmerle for such a quick reply
