### ISSUE TITLE
Not working in yukicoder

### ISSUE THREAD

**Issue by halc-git** [jmerle/competitive-companion#514]
I have confirmed that the parser is not functioning correctly for several problems and contests, as listed below:
* https://yukicoder.me/problems/no/2924
* https://yukicoder.me/problems/no/2922
* https://yukicoder.me/problems/no/1045
* https://yukicoder.me/problems/no/2322
* https://yukicoder.me/contests/261
* https://yukicoder.me/contests/486
* https://yukicoder.me/contests/502

Here is a screenshot of the error encountered at that time:
![image](https://github.com/user-attachments/assets/01727243-5f5c-4001-8361-52640ee9b72c)

**Comment by jmerle** [comment]
As for the contest parser problems: I can reproduce getting an error, but not your error. I fixed the error I got in d1e16a905a7390aa21a7ae7b0d052bbf16e834ef and will release the fix soon.

As for the problem parser problems: I think the problem is similar in nature as #515. Please make sure Google Translate or a similar extension is not enabled when using Competitive Companion. Such software tends to mangle the page's DOM, which breaks parsers like the ones in Competitive Companion. With Google Translate disabled I am not able to reproduce your error.

**Comment by halc-git** [comment]
Thank you very much. It appears that having installed [comfortable-yukicoder](https://greasyfork.org/ja/scripts/431129-comfortable-yukicoder) was one of the contributing factors.
