### ISSUE TITLE
Bun as package manager?

### ISSUE THREAD

**Issue by touhidurrr** [jmerle/competitive-companion#517]
Do you want to consider using **Bun** as a package manager? I thought I would just ask this now since **Bun** has seen large adoption lately. This will fix several issues and help us remove some `devDependencies`.

Fixes:
1. Cross platform commands. Many of the `pnpm` commands you have there does not work for me in windows. Using **Bun** can fix this issue. Because as I know commands are by default run on [**Bun** shell](https://bun.sh/docs/runtime/shell).

Improvements:
1. We can remove `tsx` and `ts-node` from devDependencies as **Bun** can run **TypeScript** files.
2. `cross-env` can be removed.

**Comment by jmerle** [comment]
> Do you want to consider using **Bun** as a package manager? I thought I would just ask this now since **Bun** has seen large adoption lately. This will fix several issues and help us remove some `devDependencies`.

I thought about it a few times when seeing influxes of Bun posts on social media and decided against it every time. Node.js (and V8) and PNPM (to a lesser degree, but still) have stood the test of time, while Bun to me is still very much in between the "peak of inflated expectations" and "trough of disillusionment" stages of the hype cycle:

![](https://github.com/user-attachments/assets/c93232fc-4716-4213-b84b-b23bd410e314)
> By Jeremykemp at English Wikipedia, CC BY-SA 3.0, https://commons.wikimedia.org/w/index.php?curid=10547051

I'm perfectly happy with the Node.js + PNPM combination that I've used in all my JS projects in the past 1.5 years. Bun needs to offer full compatibility with this set-up as well as significant improvement in part of it for me to consider moving to Bun. While Bun claims to be a drop-in Node.js replacement, it still has a bunch of incompatibilities ([1](https://bun.sh/docs/runtime/nodejs-apis) [2](https://github.com/oven-sh/bun/issues?q=sort%3Aupdated-desc%20is%3Aissue%20is%3Aopen%20v8%20api)) and its issue tracker contains hundreds of bug reports of code that reportedly works fine on Node.js but crashes on Bun ([1](https://github.com/oven-sh/bun/issues?q=is%3Aissue+is%3Aopen+segmentation+fault) [2](https://github.com/oven-sh/bun/issues?q=is%3Aissue+is%3Aopen+core+dumped)).

> 1. Cross platform commands. Many of the `pnpm` commands you have there does not work for me in windows. Using **Bun** can fix this issue. Because as I know commands are by default run on [**Bun** shell](https://bun.sh/docs/runtime/shell).

This sounds like an issue with your specific Windows set-up. I just installed Node.js and PNPM on my Windows partition and the commands that use PNPM-specific features (i.e. the `pnpm lint` and `pnpm fix` commands that use a regex) work fine for me in both PowerShell and cmd.exe. I did have some issues with commands that use single quotes, which I just fixed in 27c134d5ee38e5646943378d2fc7f38943bcfb09.

> 1. We can remove `tsx` and `ts-node` from devDependencies as **Bun** can run **TypeScript** files.
> 2. `cross-env` can be removed.

I don't know why I didn't remove `ts-node` before, but it isn't in use anymore so I removed it in c3b85dc18f8f427a82baa8424fcb6fd759194b60. As for `tsx` and `cross-env`, I'm not concerned with having those dependencies, and being able to remove them certainly doesn't trump my reasons for staying on Node.js with PNPM.
