### ISSUE TITLE
Hi, there is a problem with  UVa Online Judge' problems. (Not Parsing)

### ISSUE THREAD

**Issue by alejandrofonsecacuza** [jmerle/competitive-companion#518]
Hi, there is a problem with  UVa Online Judge' problems. (Not Parsing)

https://onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=609&page=show_problem&problem=1365

**Comment by jmerle** [comment]
Works for me:
![](https://github.com/user-attachments/assets/668f0de6-7c67-49ac-b416-af20dedf8e16)

What error are you seeing in the browser console when you try to parse the problem with Competitive Companion (F12 > Console)?

**Comment by alejandrofonsecacuza** [comment]
![Screenshot from 2024-12-15 22-46-07](https://github.com/user-attachments/assets/fd28a901-11d6-4e0b-8c54-2ebf3bc8ea1c)

**Comment by jmerle** [comment]
Aha, this appears to be the same issue as #473. I've modified the behavior of parsers that need to read PDFs in f8c705c03fd6e6791a039e10f4d46d8624b8335f so that they don't crash completely due to [Firefox bug 1757836](https://bugzilla.mozilla.org/show_bug.cgi?id=1757836), but rather try to parse as much of the problem as possible. This change will go live within 10 hours.
