### ISSUE TITLE
Currently not working on AtCoder

### ISSUE THREAD

**Issue by coder-with-style** [jmerle/competitive-companion#55]
The UI of AtCoder seems to have changed recently, and the plugin is not working on AtCoder now.

**Comment by champon1020** [comment]
I fixed :thumbsup: #56

**Comment by Ziklon** [comment]
Hoping to see the next release soon.

**Comment by jmerle** [comment]
I have just released 2.9.2 which contains the fix for this issue. It will probably be available for Firefox in about an hour, but the Chrome Web Store flagged it for human review, which can take a few days. Hopefully I'll be able to fix the reason why the Chrome Web Store keeps flagging the extension next week so bug fix releases can be released more quickly in the future.
