### ISSUE TITLE
v2.9.2 not released at Chrome Web Store

### ISSUE THREAD

**Issue by tatsumack** [jmerle/competitive-companion#59]
@jmerle 
v2.9.2 has not been released at Chrome Web Store yet. 
Is there any problem happened?

**Comment by jmerle** [comment]
2.9.2 on the Chrome Web Store is still pending review due to the extension wanting to run on all url's which is currently required to have better support for judges which use the browser's [History API](https://developer.mozilla.org/en-US/docs/Web/API/History) instead of plain links (HackerRank does this). Google does not like this very much because it requires the extension to have very broad permissions, but this has not caused any previous releases to be cancelled by Google in the reviewing stage.

Unfortunately I don't know when the review for 2.9.2 will happen, so I'll keep this issue open until 2.9.2 is released on the Chrome Web Store. I also have a solution to get rid of the requirement to run on all url's without breaking HackerRank support, which should stop the extension from being flagged for manual review on every release, and am planning to implement that this weekend.

**Comment by jmerle** [comment]
2.9.2 is now live on the Chrome Web Store and I have removed the behavior of the extension to run on all url's in 600771b77d55be030d9dac626e66723125b51866.
