### ISSUE TITLE
Typo: "Luogo" should be "Luogu"

### ISSUE THREAD

**Issue by ouuan** [jmerle/competitive-companion#62]
https://github.com/jmerle/competitive-companion/blob/b649caaa08f3967e16e849d1d32176498d107b42/src/parsers/problem/LuoguProblemParser.ts#L16

**Comment by jmerle** [comment]
Fixed in 1675312. I can't say when it goes live because the extension is pending compliance review in the Chrome Web Store and I prefer to keep versions synced between Chrome and Firefox. The compliance review should be done in a few working days according to Google and until the review is finished I cannot publish any new versions on the Chrome Web Store.

**Comment by jmerle** [comment]
This change has gone live in 2.11.0.
