### ISSUE TITLE
Individual OJ

### ISSUE THREAD

**Issue by william-song-shy** [jmerle/competitive-companion#74]
Many people like to deploy their own OJ or school OJ. Most of them will use other open source OJs such as UOJ, QDUOJ and so on. Your extension can well analyze these OJ problems and competitions, but cannot analyze Individual OJ or school OJ deployed by open source OJ.

**Comment by william-song-shy** [comment]
建议在一个拓展的界面中可以进行配置，配置IP地址和开源OJ的类型来解决这个问题

**Comment by william-song-shy** [comment]
但是我想这会是一个不小的工程

**Comment by jmerle** [comment]
First of all: I don't speak Chinese and even with Google Translate I have no idea what you meant in the second and third comment.

A similar feature was requested in #46, which I had to close because back then I believed it was impossible without using the `<all_urls>` permission, which is a permission I really don't want to use for reasons outlined in https://github.com/jmerle/competitive-companion/issues/46#issuecomment-570786180. I recently learned that it should be doable without the `<all_urls>` permission by using the `activeTab` permission correctly, although this requires some extensive changes to the core of the extension. I'll try implementing that solution somewhere next week.

**Comment by william-song-shy** [comment]
I'm sorry to reply you late.
Second comment mean you can make an extensions site which we can configuration the IP of individual OJ  and which open source OJ it was deployed by.
Third comment mean it will be hard.
Also, why can't you use the <all_urls> permission ?
Sorry I don't speak English well.

**Comment by jmerle** [comment]
Thanks for the translation. I consider the idea in your second comment outside the scope of this extension.

The reason I can't use the `<all_urls>` permission is that it will cause every Chrome Web Store release to be flagged for extensive review. While this is not something that requires additional manual action from my side, it does delay Chrome Web Store releases for weeks, which is something I want to prevent from happening.

**Comment by william-song-shy** [comment]
> Thanks for the translation. I consider the idea in your second comment outside the scope of this extension.
> 
> The reason I can't use the `<all_urls>` permission is that it will cause every Chrome Web Store release to be flagged for extensive review. While this is not something that requires additional manual action from my side, it does delay Chrome Web Store releases for weeks, which is something I want to prevent from happening.


If OJ type is not configured, how does extension determine which regular expression should be used for parsing?

**Comment by jmerle** [comment]
I have just published 2.14.0 which adds the following context menu:

![](https://i.imgur.com/4ONkEj3.png)

This makes it possible to run any parser on any website, thereby allowing the extension to be used on selfhosted or school-hosted OJ's.

The Firefox version is already live, the Chrome version is currently pending review and should be available soon.
