### ISSUE TITLE
Failed when parsing time limit and memory limit on UOJ

### ISSUE THREAD

**Issue by ouuan** [jmerle/competitive-companion#75]
As I mentioned in #64, there are many irregular time/memory limits on UOJ.

Most time limits are in this regex format: `时间限制(?:</strong>)?(?:：|:)(?:</strong>)? ?\$.*?([1-9][0-9]*).*?\$`.

Most memory limits are in this regex format: `(?:空间|内存)限制(?:</strong>)?(?:：|:)(?:</strong>)? ?\$.*?([1-9][0-9]*).*?(M|G)B.*?\$`.

However, there are still a few problems which don't satisfy these two rules, and there may be more irregular forms in the future.

**Comment by ouuan** [comment]
Here's a list of problems which don't satisfy the above regex, many of them are answer-only problems, and some of them even have ~~strikeout~~ in the limits.

```
83
100
109
212
317
349
391
392
395
411
412
413
451
452
454
457
459
462
472
473
475
476
477
481
482
483
484
485
486
494
```

**Comment by ouuan** [comment]
My suggestion is to ignore these irregular problems, and I can contact the admins to fix them.

**Comment by ouuan** [comment]
But you can use the two regexes above, they cover the most problems.

**Comment by ouuan** [comment]
The admin said he will add a regular time/memory limits system to take place of the current time/memory limits. We can wait until it's done, or use the above regexes before he's finished.

**Comment by jmerle** [comment]
I'll wait until it's done, unless that takes longer than expected (lets say 2 weeks) in which case I'll publish a version using your regex.

**Comment by jmerle** [comment]
I've improved the time and memory limit parsing for UOJ in https://github.com/jmerle/competitive-companion/compare/9f0eab3f19c8790db934b605bfe64aca2f88ae7a...197e83c239de0f33c929387c70695b72800003bb. These changes work correctly on all the problems you listed except for 451 and 452 because those problems use a non-standard way of displaying time and memory limits. In case it fails to parse the limits it now falls back to a default time limit of 1000 ms and a default memory limit of 1024 MB.

These changes will go live in 2.16.0 which I am planning to release within the next few hours.
